version: '3.0'
services:
    thingsboard:
        image: 'thingsboard/tb-postgres'
        ports:
            - '8080:9090'
            - '1883:1883'
            - '7070:7070'
            - '5432:5432'
            - '5683-5688:5683-5688/udp'
        environment:
            TB_QUEUE_TYPE: in-memory
        volumes:
            - ./data:/data
            - ./logs:/var/log/thingsboard
        restart: always
