exports.ConfigKeys = {
    FIREBASE_API_KEY: 'FIREBASE_API_KEY',
    FIREBASE_APP_ID: 'FIREBASE_APP_ID',
    FIREBASE_AUTH_DOMAIN: 'FIREBASE_AUTH_DOMAIN',
    FIREBASE_DATABASE_URL: 'FIREBASE_DATABASE_URL',
    FIREBASE_FIELD1_HUMIDITY_SENSOR_DATA_REF:
        'FIREBASE_FIELD1_HUMIDITY_SENSOR_DATA_REF',
    FIREBASE_FIELD2_HUMIDITY_SENSOR_DATA_REF:
        'FIREBASE_FIELD2_HUMIDITY_SENSOR_DATA_REF',
    FIREBASE_FIELD3_HUMIDITY_SENSOR_DATA_REF:
        'FIREBASE_FIELD3_HUMIDITY_SENSOR_DATA_REF',
    FIREBASE_FIELD4_HUMIDITY_SENSOR_DATA_REF:
        'FIREBASE_FIELD4_HUMIDITY_SENSOR_DATA_REF',
    FIREBASE_MEASUREMENT_ID: 'FIREBASE_MEASUREMENT_ID',
    FIREBASE_MESSAGING_SENDER_ID: 'FIREBASE_MESSAGING_SENDER_ID',
    FIREBASE_PROJECT_ID: 'FIREBASE_PROJECT_ID',
    FIREBASE_STORAGE_BUCKET: 'FIREBASE_STORAGE_BUCKET',
    FIREBASE_WEATHER_STATION_DATA_REF: 'FIREBASE_WEATHER_STATION_DATA_REF',
    SERVER_DOMAIN: 'SERVER_DOMAIN',
    THINGSBOARD_FIELD1_HUMIDITY_SENSOR_ACCESS_TOKEN:
        'THINGSBOARD_FIELD1_HUMIDITY_SENSOR_ACCESS_TOKEN',
    THINGSBOARD_FIELD2_HUMIDITY_SENSOR_ACCESS_TOKEN:
        'THINGSBOARD_FIELD2_HUMIDITY_SENSOR_ACCESS_TOKEN',
    THINGSBOARD_FIELD3_HUMIDITY_SENSOR_ACCESS_TOKEN:
        'THINGSBOARD_FIELD3_HUMIDITY_SENSOR_ACCESS_TOKEN',
    THINGSBOARD_FIELD4_HUMIDITY_SENSOR_ACCESS_TOKEN:
        'THINGSBOARD_FIELD4_HUMIDITY_SENSOR_ACCESS_TOKEN',
    THINGSBOARD_WEATHER_STATION_ACCESS_TOKEN:
        'THINGSBOARD_WEATHER_STATION_ACCESS_TOKEN',
};
